### ISSUE TITLE
Background profiler crashed the server

### ISSUE THREAD

**Issue by masmc05** [lucko/spark#285] opened 2022-12-28 11:04 UTC
[hs_err_pid2589209.log](https://github.com/lucko/spark/files/10313844/hs_err_pid2589209.log)

**Comment by skerit** [comment] 2022-12-28 11:39
I'm also getting the same segfault because of Spark

**Comment by lucko** [comment] 2023-02-12 12:59
Duplicate of https://github.com/lucko/spark/issues/251

**Closed by lucko** 2023-02-12 12:59 UTC
