### ISSUE TITLE
Server just crashs randomly when started.

### ISSUE THREAD

**Issue by kxmpxtxnt** [lucko/spark#469] opened 2024-11-02 21:07 UTC
### Description

Hey guys,
when starting my minecraft server its randomy just crashs with this log. 
Every line of the log before is perfectly normal which is why I didn`t include it,

### Reproduction Steps

I have no idea I'am sorry

### Expected Behaviour

Start without crashing

### Platform Information

* Minecraft Version: 1.21.1
* Platform Type: Paper
* Platform Brand: Paper
* Platform Version: latest

### Spark Version

latest

### Logs and Configs

https://pastes.dev/RbqRQSmrfg

**Comment by SirYwell** [comment] 2024-11-03 09:09
Duplicate of #461

**Closed** 2024-11-21 09:17 UTC
Labels: bug
