### ISSUE TITLE
Mods cause JVM crash on linux

### ISSUE THREAD

**Issue by cylian914** [lucko/spark#292] opened 2023-01-15 18:57 UTC
Hi, Spark on forge client crash my JVM instance when i load/generate a world, using openJDK on archlinux.
Here the JVM crash report: https://pastebin.com/UHSZXKTh

Minecraft version: 1.19.2
Forge version: 43.2.3
Spark version: 1.10.17-forge

i hope it help

**Comment by ApionXD** [comment] 2023-02-02 20:26
I also have this issue. 

Java: openjdk version "17.0.5" 2022-10-18
MC Version: Paper 1.19.3-386
Spark Version: 1.10.29-bukkit
JVM Crash Report: https://pastebin.com/KiHXMuDB

Interestingly, I am ALSO on Arch.

**Comment by ApionXD** [comment] 2023-02-02 20:51
I just tried with an Adoptium build of Java, and I don't have the same issue. 

Java Version: OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)

**Comment by ToastedWookiee** [comment] 2023-02-02 23:29
Arch updated from 17.0.5 to 17.0.6 on 1/18, since then my system has not had any problems with Spark, which used to crash as well.

**Comment by lucko** [comment] 2023-02-12 13:08
Duplicate of https://github.com/lucko/spark/issues/251

**Closed by lucko** 2023-02-12 13:08 UTC
