### ISSUE TITLE
Velocity: Exception executing sparkv profiler --stop

### ISSUE THREAD

**Issue by arima0k** [lucko/spark#236] opened 2022-07-29 13:49 UTC
Every time I must execute `sparkv profiler --stop` twice first time never work. (https://spark.lucko.me/0EmZGwJymJ)

Console log:
```
[08:41:31 INFO]: [⚡] The active profiler has been stopped! Uploading results...
[08:41:31 ERROR] [spark]: Exception occurred whilst executing a spark command
[08:41:31 ERROR]: java.nio.BufferUnderflowException
[08:41:31 ERROR]:       at java.base/java.nio.Buffer.nextGetIndex(Buffer.java:699)
[08:41:31 ERROR]:       at java.base/java.nio.DirectByteBuffer.get(DirectByteBuffer.java:324)
[08:41:31 ERROR]:       at me.lucko.spark.common.sampler.async.jfr.JfrReader.getVarint(JfrReader.java:455)
[08:41:31 ERROR]:       at me.lucko.spark.common.sampler.async.jfr.JfrReader.readConstantPool(JfrReader.java:280)
[08:41:31 ERROR]:       at me.lucko.spark.common.sampler.async.jfr.JfrReader.readChunk(JfrReader.java:216)
[08:41:31 ERROR]:       at me.lucko.spark.common.sampler.async.jfr.JfrReader.<init>(JfrReader.java:80)
[08:41:31 ERROR]:       at me.lucko.spark.common.sampler.async.AsyncSampler.aggregateOutput(AsyncSampler.java:186)
[08:41:31 ERROR]:       at me.lucko.spark.common.sampler.async.AsyncSampler.toProto(AsyncSampler.java:166)
[08:41:31 ERROR]:       at me.lucko.spark.common.command.modules.SamplerModule.handleUpload(SamplerModule.java:306)
[08:41:31 ERROR]:       at me.lucko.spark.common.command.modules.SamplerModule.profilerStop(SamplerModule.java:300)
[08:41:31 ERROR]:       at me.lucko.spark.common.command.modules.SamplerModule.profiler(SamplerModule.java:134)
[08:41:31 ERROR]:       at me.lucko.spark.common.SparkPlatform.executeCommand0(SparkPlatform.java:382)
[08:41:31 ERROR]:       at me.lucko.spark.common.SparkPlatform.lambda$executeCommand$2(SparkPlatform.java:292)
[08:41:31 ERROR]:       at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$1(VelocityScheduler.java:229)
[08:41:31 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[08:41:31 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[08:41:31 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by lucko** [comment] 2022-08-07 18:06
Does it reliably not work?

Please share your operating system version, Java version, velocity version

**Comment by arima0k** [comment] 2022-08-08 13:53
`sparkv profiler --stop` only works if I execute a second time. 

- Ubuntu Server 20.04 LTS | Linux 5.15.0-43-generic
- openjdk version "17.0.4" 2022-07-19 LTS
    OpenJDK Runtime Environment Corretto-17.0.4.8.1 (build 17.0.4+8-LTS)
- Velocity 3.1.2-SNAPSHOT (git-6496983c-b171)

**Comment by lucko** [comment] 2022-09-04 09:45
Closing as a duplicate of https://github.com/lucko/spark/issues/225, please see my comment there

**Closed by lucko** 2022-09-04 09:45 UTC
Labels: bug
