### ISSUE TITLE
Small format issue

### ISSUE THREAD

**Issue by SlimeDog** [lucko/spark#168] opened 2022-01-31 15:53 UTC
Spigot 1.18.1-3417
spark 1.8.0-275 or 276

Last line sometimes contains extra characters (sometimes 3, sometimes 2, sometimes 0). This does not occur with same spark version on
- Paper 1.18.1-177
- Waterfall 1.18-477
- velocity 3.1.1-98
```
>spark healthreport
[07:47:53] [Craft Scheduler Thread - 7/INFO]: [⚡] Generating server health report...
[07:47:53] [Craft Scheduler Thread - 7/INFO]: 
[07:47:53] [Craft Scheduler Thread - 7/INFO]: > TPS from last 5s, 10s, 1m, 5m, 15m:
[07:47:53] [Craft Scheduler Thread - 7/INFO]:     *20.0, *20.0, *20.0, 19.88, 19.96
[07:47:53] [Craft Scheduler Thread - 7/INFO]: 
[07:47:53] [Craft Scheduler Thread - 7/INFO]: > CPU usage from last 10s, 1m, 15m:
[07:47:53] [Craft Scheduler Thread - 7/INFO]:     6%, 8%, 33%  (system)
[07:47:53] [Craft Scheduler Thread - 7/INFO]:     7%, 7%, 28%  (process)
[07:47:53] [Craft Scheduler Thread - 7/INFO]: 
[07:47:53] [Craft Scheduler Thread - 7/INFO]: > Memory usage:
[07:47:53] [Craft Scheduler Thread - 7/INFO]:     4.2 GB / 8.0 GB   (52%)
[07:47:53] [Craft Scheduler Thread - 7/INFO]:     [┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃╻╻╻╻╻╻╻╻╻╻╻╻╻╻╻╻╻╻╻╻╻╻╻╻╻╻╻╻╻]
[07:47:53] [Craft Scheduler Thread - 7/INFO]: 
[07:47:53] [Craft Scheduler Thread - 7/INFO]: > Disk usage:
[07:47:53] [Craft Scheduler Thread - 7/INFO]:     58.1 GB / 77.7 GB   (74%)
[07:47:53] [Craft Scheduler Thread - 7/INFO]:     [┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃┃���┃┃┃┃┃┃┃┃┃┃╻╻╻╻╻╻╻╻╻╻╻╻╻╻╻╻]
```

**Comment by lucko** [comment] 2022-02-03 19:04
Hmm this is going to be difficult to track down.

It will either be a Spigot bug or an issue with adventure (the library spark uses for chat formatting)

**Comment by SlimeDog** [comment] 2022-02-03 19:53
It certainly isn't high priority. I just thought you would want to know. And just for fun, it's transient.

**Comment by lucko** [comment] 2022-05-05 20:30
Closing as wontfix for now, either way the issue is not with spark - unfortunately I don't have time to debug, sorry!

**Closed by lucko** 2022-05-05 20:30 UTC
Labels: bug

**Comment by SlimeDog** [comment] 2022-05-30 22:30
Whatever changed in spark build 308 or Spigot releases that week seems to have resolved the problem. :)
