### ISSUE TITLE
NoSuchMethodError on stop profiler

### ISSUE THREAD

**Issue by SlimeDog** [lucko/spark#63] opened 2020-07-20 05:02 UTC
Spigot 1.16.1 (Jenkins 2831)
Spark 1.4.2

Spark ran for 6 minutes, then on stop
```
>spark profiler --stop
[22:00:52] [Server thread/INFO]: [⚡] The active sampling operation has been stopped! Uploading results...
[22:00:52] [Craft Scheduler Thread - 234/WARN]: [spark] Plugin spark v1.4.2 generated an exception while executing task 92356
java.lang.NoSuchMethodError: org.bukkit.Server.getMinecraftVersion()Ljava/lang/String;
        at me.lucko.spark.bukkit.BukkitPlatformInfo.getMinecraftVersion(BukkitPlatformInfo.java:50) ~[?:?]
        at me.lucko.spark.common.platform.PlatformInfo.toData(PlatformInfo.java:43) ~[?:?]
        at me.lucko.spark.common.sampler.Sampler.toProto(Sampler.java:167) ~[?:?]
        at me.lucko.spark.common.sampler.Sampler.formCompressedDataPayload(Sampler.java:192) ~[?:?]
        at me.lucko.spark.common.command.modules.SamplerModule.lambda$handleUpload$5(SamplerModule.java:270) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.1.jar-2020-07-18-1607:git-Spigot-0509002-6b95d59]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.1.jar-2020-07-18-1607:git-Spigot-0509002-6b95d59]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by lucko** [comment] 2020-07-21 14:35
Duplicate of #59, 1bf26ed4e9cd923ec1234804a3a3668afbb63876

**Closed by lucko** 2020-07-21 14:35 UTC
